"""End-to-end DAG run via `dag.test()` for the Bronze ingest DAG only.

The silver/gold DAGs are generated by Cosmos and would invoke real dbt-duckdb
at test time — that's covered by `dbt test` in the data_quality DAG, not here.

Needs Airflow installed → run inside a container:
    docker compose exec airflow-scheduler pytest /opt/airflow/tests/test_dag_test_mode.py
"""
from __future__ import annotations

import pytest

pytest.importorskip("airflow")


def test_ingest_bronze_runs_end_to_end(monkeypatch):
    import medallion.ingest as ingest_mod

    calls: list[tuple[str, str]] = []

    def fake_ingest(table: str, dt: str | None = None) -> dict:
        calls.append((table, dt))
        return {"rows": 0}

    monkeypatch.setattr(ingest_mod, "ingest_table", fake_ingest)

    import bronze_dag
    monkeypatch.setattr(bronze_dag, "ingest_table", fake_ingest)

    bronze_dag.dag.test()

    # One call per source table.
    from medallion.ingest import TABLES
    assert {c[0] for c in calls} == set(TABLES)
    # Every call resolved a `dt` from data_interval_end — not None.
    assert all(c[1] is not None for c in calls)
