"""Operations Dashboard — job health, failed runs, SLA, cold-start metrics."""

import marimo

__generated_with = "0.10.0"
app = marimo.App(width="full", app_title="Ops Dashboard")


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _(mo):
    mo.md(
        """
        # Operations Dashboard
        **Source**: `system.lakeflow.job_run_timeline` + `system.lakeflow.jobs`

        > **Local mode**: reads from `../data/system/` Delta tables generated by
        > `scripts/generate_synthetic_system_data.py`.
        > On real Databricks, point `DATA_ROOT` to `system` and use the actual catalog.
        """
    )
    return


@app.cell
def _():
    from pathlib import Path

    from delta import configure_spark_with_delta_pip
    from pyspark.sql import SparkSession
    from pyspark.sql import functions as F

    DATA_ROOT = Path(__file__).parent.parent / "data" / "system"

    builder = (
        SparkSession.builder.appName("ops-dashboard")
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
        .config(
            "spark.sql.catalog.spark_catalog",
            "org.apache.spark.sql.delta.catalog.DeltaCatalog",
        )
        .config("spark.driver.memory", "2g")
    )
    spark = configure_spark_with_delta_pip(builder).getOrCreate()
    spark.sparkContext.setLogLevel("WARN")

    runs = spark.read.format("delta").load(str(DATA_ROOT / "lakeflow" / "job_run_timeline"))
    jobs = spark.read.format("delta").load(str(DATA_ROOT / "lakeflow" / "jobs"))

    job_names = (
        jobs.groupBy("job_id")
        .agg(F.last("name").alias("job_name"), F.last("run_as_user_name").alias("run_as"))
    )
    return DATA_ROOT, F, Path, builder, configure_spark_with_delta_pip, job_names, jobs, runs, spark


@app.cell
def _(F, job_names, mo, runs):
    import pandas as pd

    failed = (
        runs.filter(F.col("result_state").isin(["FAILED", "TIMED_OUT", "ERROR", "BLOCKED"]))
        .join(job_names, "job_id", "left")
        .select(
            "job_name",
            "run_id",
            "result_state",
            "termination_code",
            "period_start_time",
            F.round(F.col("run_duration_seconds") / 60.0, 1).alias("duration_min"),
            F.round(F.col("setup_duration_seconds") / 60.0, 1).alias("setup_min"),
        )
        .orderBy(F.col("period_start_time").desc())
        .limit(100)
        .toPandas()
    )

    mo.md(f"## Failed Runs — last 100\n**{len(failed)} failures found**")
    return failed, pd


@app.cell
def _(failed, mo):
    mo.ui.table(failed, selection=None)
    return


@app.cell
def _(F, job_names, mo, runs):
    summary = (
        runs.filter(F.col("result_state").isNotNull())
        .join(job_names, "job_id", "left")
        .groupBy("job_name", "result_state")
        .agg(F.count("*").alias("count"))
        .orderBy("job_name", "result_state")
        .toPandas()
    )

    mo.md("## Run Outcome Summary by Job")
    return (summary,)


@app.cell
def _(mo, summary):
    mo.ui.table(summary, selection=None)
    return


@app.cell
def _(F, job_names, mo, runs):
    cold_start = (
        runs.filter(F.col("result_state") == "SUCCEEDED")
        .join(job_names, "job_id", "left")
        .groupBy("job_name")
        .agg(
            F.round(F.avg("setup_duration_seconds") / 60.0, 1).alias("avg_cold_start_min"),
            F.round(F.avg("run_duration_seconds") / 60.0, 1).alias("avg_run_min"),
            F.round(
                F.avg("setup_duration_seconds") * 100.0
                / F.when(F.avg("run_duration_seconds") == 0, None).otherwise(
                    F.avg("run_duration_seconds")
                ),
                1,
            ).alias("cold_start_pct"),
            F.count("*").alias("run_count"),
        )
        .orderBy(F.col("cold_start_pct").desc())
        .toPandas()
    )

    mo.md(
        """
        ## Cold-Start Analysis
        *Pain Point 1*: what fraction of runtime is spent waiting for the cluster to start?
        """
    )
    return (cold_start,)


@app.cell
def _(cold_start, mo):
    mo.ui.table(cold_start, selection=None)
    return


@app.cell
def _(mo):
    mo.md(
        """
        ---
        **Next**: open `02_cost_attribution.py` to see DBU spend by team and job.
        """
    )
    return


if __name__ == "__main__":
    app.run()
