#!/usr/bin/env bash
# Sync the reusable `lakehouse` package + table registry from the sibling
# databricks_lakehouse project into this project's build context.
#
# The medallion logic (bronze/silver/gold/config) is reused VERBATIM — we never
# edit it here. Only the execution boundary (embedded Spark -> Spark-on-K8s)
# differs, and that lives in jobs/ and dags/, not in the package.
#
# Docker build contexts cannot follow symlinks outside the context root, so we
# copy rather than symlink. This is idempotent (rsync --delete on src/lakehouse).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$HERE/../databricks_lakehouse}"

# The package + registry + generator + init_ods.sql are VENDORED IN (committed),
# so this project builds standalone. When the databricks_lakehouse sibling is
# present we refresh those files from it (steps 1-4); when it isn't, we skip the
# refresh and build from the committed copies. Either way we re-render the
# file-derived ConfigMaps (step 5) from whatever is on disk.
if [[ -d "$SRC/src/lakehouse" ]]; then
  echo "Refreshing vendored lakehouse files from: $SRC"

  # 1. The package (verbatim).
  mkdir -p "$HERE/lakehouse/src"
  rsync -a --delete \
    --exclude '__pycache__' --exclude '*.pyc' \
    "$SRC/src/lakehouse/" "$HERE/lakehouse/src/lakehouse/"

  # 2. The table registry (verbatim) — drives dynamic DAG tasks AND Spark jobs.
  cp "$SRC/config/table_registry.yaml" "$HERE/lakehouse/config/table_registry.yaml"

  # 3. The data generator (verbatim) — reused by the seed Job.
  cp "$SRC/scripts/generate_source_data.py" "$HERE/lakehouse/generate_source_data.py"

  # 4. init_ods.sql (verbatim) — used by the shared Postgres init ConfigMap.
  cp "$SRC/scripts/init_ods.sql" "$HERE/lakehouse/init_ods.sql"
else
  echo "Sibling project not found at $SRC — using committed (vendored) copies."
  # Sanity-check the vendored snapshot is actually present before continuing.
  if [[ ! -d "$HERE/lakehouse/src/lakehouse" ]]; then
    echo "ERROR: no vendored package at lakehouse/src/lakehouse and no sibling" >&2
    echo "project to sync from. Pass one: scripts/sync-lakehouse.sh /path/to/databricks_lakehouse" >&2
    exit 1
  fi
fi

# 5. Render the file-derived ConfigMaps as STATIC manifests under k8s/config/.
#    These wrap synced content (table_registry.yaml, init_ods.sql) so they are
#    generated here rather than hand-edited — keeping a single source of truth —
#    but the result is a real, inspectable manifest applied via `kubectl apply`.
#    (kubectl --dry-run=client runs fully offline; no cluster needed.)
GEN_HDR="# GENERATED by scripts/sync-lakehouse.sh — DO NOT EDIT.
# Source of truth: lakehouse/config/ (dev/prod.yaml authored here;
# table_registry.yaml + init_ods.sql synced from databricks_lakehouse).
# Regenerate with: make sync"

mkdir -p "$HERE/k8s/config"

{ echo "$GEN_HDR"; \
  kubectl create configmap lakehouse-config -n lakehouse \
    --from-file="$HERE/lakehouse/config/" \
    --dry-run=client -o yaml; \
} > "$HERE/k8s/config/lakehouse-config.generated.yaml"

{ echo "$GEN_HDR"; \
  kubectl create configmap pg-init -n lakehouse \
    --from-file=01_init_ods.sql="$HERE/lakehouse/init_ods.sql" \
    --dry-run=client -o yaml; \
} > "$HERE/k8s/config/pg-init.generated.yaml"

echo "Sync complete:"
echo "  lakehouse/src/lakehouse/        (package)"
echo "  lakehouse/config/table_registry.yaml"
echo "  lakehouse/generate_source_data.py"
echo "  lakehouse/init_ods.sql"
echo "  k8s/config/lakehouse-config.generated.yaml   (static ConfigMap manifest)"
echo "  k8s/config/pg-init.generated.yaml            (static ConfigMap manifest)"
echo
echo "NOTE: dev.yaml / prod.yaml are authored in this project (different"
echo "      s3_endpoint for in-cluster MinIO) and are NOT overwritten by sync."
