[project]
name = "polars-marimo-guide"
version = "0.1.0"
description = "Python Polars: The Definitive Guide, in marimo!"
readme = "README.md"
authors = [
    { name = "Jeroen Janssens", email = "jeroen@jeroenjanssens.com" },
    { name = "Thijs Nieuwdorp", email = "thijsnieuwdorp@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chardet>=7.0.1",
    "connectorx>=0.4.5",
    "marimo[recommend,recommended]>=0.20.4",
    "maturin>=1.12.6",
    "numpy>=2.4.3",
    "ruff>=0.15.5",
]
